Counter
FE38-Front-End/DashaNalivayko-React pull request #1
Opened 2021-02-25 18:58 UTC by dashanalivayko

Approve please)

2021-03-01 19:35 UTC, akhovbok requested changes

2021-03-01 19:35 UTC, akhovbok commented on counter/src/Counter.js
> +    this.state = {counter: 0};
{counter: 0}; два раза повторяется на странице, намек понятен?

2021-03-01 19:35 UTC, akhovbok commented on counter/src/Counter.js
> +        <button onClick={this.clickPlus} className="plus"><img src={plus} alt="plus"/></button>
хотелось бы видеть несколько компонентов вместо одного большого

2021-03-03 19:59 UTC, akhovbok requested changes
сперва удали папку node_modules с репозитория и добавь гитигнор а потом тебе будет апрув

2021-03-04 07:09 UTC, dashanalivayko commented
> сперва удали папку node_modules с репозитория и добавь гитигнор а потом тебе будет апрув

я же предпоследним комитом это сделала. До этого случайно модалс отправила, но перед реквестом удалила... проверила и не нашла эту папку, где ты ее видел?

2021-03-04 07:21 UTC, closed without merging